plugins {
    id 'groovy'
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

// Load local overrides
def localPropsFile = file('gradle-local.properties')
if (localPropsFile.exists()) {
    localPropsFile.withInputStream { stream ->
        Properties props = new Properties()
        props.load(stream)
        props.each { key, value ->
            project.ext.set(key.toString(), value)
        }
    }
}

final int javaVersion = 11

allprojects {
    group = groupName
    version = "2.9.6"
    repositories {
        mavenLocal()
        mavenCentral()
        maven { // Sonatype Snapshots
            url = "https://s01.oss.sonatype.org/content/repositories/snapshots"
        }
    }
}

/**
 * Returns project description
 * @param name
 * @return
 */
static String getProjectDescription(String name) {
    String desc = ""
    switch (name) {
        case "core":
            desc = "Basic functionality that is usually needed " +
                "in any project. For example, configuration, " +
                "logging, executing commands, controlling " +
                "services and displaying colors in console."
            break
        case "log":
            desc = "SLF4J colorful logger with many options and easy to use." +
                "You can add customized loggers and personalize " +
                "the way your logs look."
            break
        case "etc":
            desc = "Extra functionality which is usually very " +
                "useful in any project. For example, monitoring " +
                "Hardware, compressing or decompressing data, " +
                "store data in memory cache, manage system " +
                "configuration in a multithreading safe environment " +
                "(BerkeleyDB or Redis), simple operations with " +
                "bytes, etc."
            break
        case "db":
            desc = "Manage databases as MySQL/MariaDB, SQLite, " +
                "Postgresql, Oracle, SQLServer and more. Create, store and " +
                "perform CRUD operations to data without having " +
                "to use SQL (a light-weight implementation as " +
                "alternative to Hibernate) or use the Fluid SQL builder."
            break
        case "net":
            desc = "Classes related to networking. For example, " +
                "sending emails through SMTP, connecting or " +
                "creating TCP/UDP servers, getting network " +
                "interfaces and perform netmask calculations, etc."
            break
        case "serial":
            desc = "Manage serial communication easily. It uses " +
                "JSSC library on the background."
            break
        case "web":
            desc = "Create restful HTTP (GET, POST, PUT, DELETE, etc) " +
                "or SSE / WebSocket application services. Manage JSON " +
                "data from and to the server easily. It is build " +
                "on top of Jetty library, so it is very powerful " +
                "but designed to be elegant and easy to use."
            break
        case "crypt":
            desc = "Offers methods to encode, decode, hash and encrypt " +
                "information. It is built using the BouncyCastle " +
                "library and simplifying its usage without reducing " +
                "its safety."
            break
        case "thread":
            desc = "Manage Tasks (Threads) with priority and watches " +
                "its performance. You can create parallel processes " +
                "easily, processes which are executed in an interval, " +
                "as a service or after a specified amount of time. " +
                "This module is very useful to help you to identify " +
                "bottlenecks and to manage your main threads in a " +
                "single place."
            break
        case "term":
            desc = "Anything related to terminal is in this module " +
                "(except AnsiColor, which is in core). It uses JLine " +
                "to help you create interactive terminal (console) " +
                "applications easily. It also contains some tools " +
                "to display progress with colors."
            break
        case "img":
            desc = "Classes for using Images (BufferedImage, File, FrameShot) " +
                "and non-opencv related code, trying to keep dependencies " +
                "to a minimum. It also includes common geometric operations."
            break
    }
    return desc
}
nexusPublishing {
    repositories {
        sonatype {
            // see https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#configuration
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
        }
    }
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(javaVersion)
    }
}

subprojects {
    apply plugin: 'groovy'
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'signing'

    boolean isDev = version.toString().contains("SNAPSHOT")
    boolean publishDev = ! version.toString().contains("DEBUG")

    configurations {
        documentation
    }
    dependencies {
        def groovyVer = "4.0.32" // Also in module etc
        def groovyExt = "4.0.30.14"
        def spock = "2.4-M4-groovy-4.0"

        //Link it so we can choose version
        compileOnly "org.apache.groovy:groovy:${groovyVer}"
        //compileOnly "org.apache.groovy:groovy-contracts:${groovyVer}"
        //compileOnly "org.apache.groovy:groovy-typecheckers:${groovyVer}"

        // Always include groovy-extend and expose it to consumers:
        api "com.intellisrc:groovy-extend:${groovyExt}"

        testImplementation "org.apache.groovy:groovy:${groovyVer}"
        testImplementation "org.spockframework:spock-core:${spock}"
        // Fixes "The automatic loading of test framework implementation dependencies has been deprecated." for Gradle 9
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }
    tasks.withType(Groovydoc).configureEach {
        classpath += project.configurations.documentation
    }
    java {
        if(!isDev || publishDev) {
            withSourcesJar()
            withJavadocJar()
        }
    }
    publishing {
        publications {
            register("mavenJava", MavenPublication) {
                from(components["java"] as SoftwareComponent)

                artifactId = project.name
                groupId = groupName

                pom {
                    name.set(projectName.toString() + " : " + project.name.capitalize() + " Module")
                    description.set(getProjectDescription(project.name) ?: projectDescription.toString())
                    url.set(projectURL.toString())
                    inceptionYear.set(projectSince.toString())
                    licenses {
                        license {
                            name = 'GNU General Public License v3.0'
                            url = 'https://www.gnu.org/licenses/gpl-3.0.en.html'
                            distribution = 'repo'
                        }
                    }
                    developers {
                        developer {
                            id.set(authorId.toString())
                            name.set(authorName.toString())
                            email.set(authorEmail.toString())
                        }
                    }
                    scm {
                        url.set(projectURL.toString())
                        connection.set("scm:git:${projectURL}.git")
                        developerConnection.set("scm:git:${projectDevURL}")
                    }
                }
            }
        }
    }
    signing {
        if(! isDev || publishDev) {
            sign publishing.publications.mavenJava
        }
    }
    tasks.withType(JavaCompile).configureEach {
        options.release.set(javaVersion) // Ensures bytecode compatibility with Java
    }
    tasks.withType(Test).configureEach {
        // Use JUnit Platform for unit tests.
        useJUnitPlatform()
    }
}
