import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform

dependencies {
    def os = DefaultNativePlatform.currentOperatingSystem
    def arch = DefaultNativePlatform.currentArchitecture

    def jetty = "12.1.7" //Jetty 12 requires Java 17
    api project(':etc')
    api project(':net')
    api "org.eclipse.jetty:jetty-server:${jetty}"
    api "org.eclipse.jetty.http2:jetty-http2-server:${jetty}"
    api "org.eclipse.jetty.http3:jetty-http3-server:${jetty}"
    // HTTP2 + HTTP3
    api "org.eclipse.jetty:jetty-alpn-server:${jetty}"
    api "org.eclipse.jetty:jetty-alpn-conscrypt-server:${jetty}"
    // HTTP3
    api "org.eclipse.jetty.quic:jetty-quic-server:${jetty}"

    api "org.eclipse.jetty.ee10:jetty-ee10-servlets:${jetty}"
    api "org.eclipse.jetty.websocket:jetty-websocket-jetty-client:${jetty}"
    api "org.eclipse.jetty.websocket:jetty-websocket-jetty-server:${jetty}"
    api "org.eclipse.jetty.ee10.websocket:jetty-ee10-websocket-jakarta-server:${jetty}"

    // NOTE: To enable Brotli compression, you may need to add this to your project:
    // implementation "com.nixxcode.jvmbrotli:jvmbrotli:$jvmbrotli"
    // And depending on your platform:
    // implementation "com.nixxcode.jvmbrotli:jvmbrotli-linux-x86-amd64:$jvmbrotli""
    //
    // The following enables Brotli only during development (automatically detecting your development platform):
    def jvmbrotli = "0.2.0"
    def jvmBrotliMain = "com.nixxcode.jvmbrotli:jvmbrotli:$jvmbrotli"
    def jvmBrotliLib = ""
    switch (true) {
        case os.windows && arch.i386:
            jvmBrotliLib = "com.nixxcode.jvmbrotli:jvmbrotli-win32-x86:$jvmbrotli"
            break
        case os.windows && arch.amd64:
            jvmBrotliLib = "com.nixxcode.jvmbrotli:jvmbrotli-win32-x86-amd64:$jvmbrotli"
            break
        case os.macOsX && arch.amd64:
            jvmBrotliLib = "com.nixxcode.jvmbrotli:jvmbrotli-darwin-x86-amd64:$jvmbrotli"
            break
        case os.linux && arch.amd64:
            jvmBrotliLib = "com.nixxcode.jvmbrotli:jvmbrotli-linux-x86-amd64:$jvmbrotli"
            break
        default:
            println "No suitable driver of Brotli found for current " +
                "OS (${os.displayName}) and architecture (${arch.displayName}). Brotli will be disabled."
    }
    compileOnly jvmBrotliMain
    testImplementation jvmBrotliMain
    if(jvmBrotliLib) {
        compileOnly jvmBrotliLib
        testImplementation jvmBrotliLib
    }
    testImplementation project(':thread')
    testImplementation project(':crypt')

    def okhttp = "5.3.2"
    testImplementation "com.squareup.okhttp3:okhttp:${okhttp}"
    testImplementation "com.squareup.okhttp3:okhttp-sse:${okhttp}"
}