package com.intellisrc.db.jdbc

import spock.lang.Ignore

/**
 * @since 18/06/15.
 */
@Ignore //Ran manually
class FirebirdTest extends JDBCTest {
    String getTableCreate(String name = "test") {
        return """CREATE TABLE $name (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(10) NOT NULL,
                version FLOAT,
                active CHAR,
                updated DATE
        );"""
    }

    /**
     * Launch test:
     * docker run --name firebird -e ISC_PASSWORD=test -e FIREBIRD_DATABASE=test -e FIREBIRD_USER=test -e FIREBIRD_PASSWORD=test -p 127.0.0.1:3050:3050 -d jacobalberty/firebird:3.0
     * @return
     */
    @Override
    JDBC getDB() {
        return new Firebird(
            user    : "test",
            hostname: "localhost",
            password: "test",
            dbname  : "/firebird/data/test",
        )
    }
}