package com.intellisrc.db.jdbc

import com.intellisrc.core.Config
import com.intellisrc.core.Log
import com.intellisrc.db.ColumnDefinition
import com.intellisrc.db.TableDefinition
import com.intellisrc.db.auto.AutoJDBC
import com.intellisrc.db.auto.Model
import groovy.transform.CompileStatic

import java.lang.reflect.Method
import java.lang.reflect.Modifier
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime

import static com.intellisrc.db.ColumnDefinition.UNLIMITED

/**
 * H2 Database
 * @since 2022/12/5.
 * To access the console:
 *  java -cp h2-*.jar org.h2.tools.Server
 *
 * Additional settings:
 * db.h2H2.
 */
@CompileStatic
@SuppressWarnings('GetterMethodCouldBeProperty')
class H2 extends JDBCServer implements AutoJDBC {
    // Absolute path to database
    String dbname = ""
    String user = "sa"
    String password = ""
    String hostname = ""
    int port = 1521
    String cipher = "" // AES
    String driver = "org.h2.Driver"
    boolean supportsReplace = true
    String catalogSearchName = null
    String schemaSearchName = "PUBLIC"
    String fieldsQuotation = '`'
    String tablesQuotation = '`'

    boolean memory = Config.any.get("db.h2.memory", false)

    @Override
    String getTableSearchName(String table) {
        return table.toUpperCase()
    }

    @Override
    Map getParameters() {
        Map connParams = Config.any.get("db.h2.params", [:] + params)
        if(cipher) {
            connParams.CIPHER = cipher
        }
        return connParams
    }

    @Override
    String getTablesQuery() {
        return "SELECT LOWER(table_name) FROM information_schema.tables WHERE table_schema = 'PUBLIC'"
    }

    @Override
    String getConnectionString() {
        return connectionURI ?: "jdbc:h2:" + (memory ? "mem:${dbname ?: 'default'};DB_CLOSE_DELAY=-1" :
            (hostname ? "tcp://$hostname:$port/$dbname" + "?" + parameters.toQueryString() : "$dbname"))
    }

    @Override
    String getDropTableQuery(String table) {
        return "DROP TABLE $table CASCADE"
    }

    // QUERY BUILDING & AUTO-DDL -------------------------

    @Override
    String getCreateTableSQL(String tableName, TableDefinition definitions = [] as TableDefinition) {
        List<String> defs = []
        List<ColumnDefinition> pks = definitions.pks
        boolean isMultiplePks = definitions.hasMultiplePk()

        definitions.each { ColumnDefinition col ->
            List<String> parts = ["`${col.name}`".toString(), getColumnDefinitionCustom(col)]

            if (col.defaultValue) {
                parts << getDefaultQuery(col)
            } else if (!col.nullable && !col.primaryKey) {
                parts << "NOT NULL"
            }

            if (col.autoIncrement && !isMultiplePks) {
                parts << "GENERATED BY DEFAULT AS IDENTITY"
            }

            if (col.primaryKey && !isMultiplePks) {
                parts << "PRIMARY KEY"
            }

            if (col.unique && !col.uniqueGroup) {
                parts << "UNIQUE"
            }
            defs << parts.join(' ')
        }

        if (isMultiplePks) {
            defs << "PRIMARY KEY (" + pks.collect { "`${it.name}`" }.join(",") + ")"
        }

        // Composite Unique Groups
        Map<String, List<String>> uniqueGroups = definitions.uniqueGroups
        if (!uniqueGroups.isEmpty()) {
            uniqueGroups.each { String groupName, List<String> columns ->
                defs << "CONSTRAINT `${tableName}_${groupName}` UNIQUE (${columns.collect { "`${it}`" }.join(',')})".toString()
            }
        }

        // Foreign Keys
        String fks = definitions.collect { getForeignKey(tableName, it) }.findAll { it }.join(",\n")
        if (fks) {
            defs << fks
        }

        return "CREATE TABLE IF NOT EXISTS `${tableName}` (\n" + defs.join(",\n") + "\n)"
    }

    /*
    MERGE INTO users (id, name, email) KEY(id) VALUES (1, 'Alice', 'alice@example.com');
     */
    String getReplaceQuery(String table, String values) {
        return "MERGE INTO $table $values" //FIXME
    }

    @Override
    String getTurnFK(boolean on) {
        return String.format("SET REFERENTIAL_INTEGRITY %s", on ? "TRUE" : "FALSE")
    }

    @Override
    String getCopyTableStructureSQL(String from, String to, TableDefinition columns = [] as TableDefinition) {
        return "CREATE TABLE `${to}` AS SELECT * FROM `${from}` WHERE 1=0"
    }

    @Override
    String getVersionRead(String table) {
        return "SELECT REMARKS FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='PUBLIC' AND TABLE_NAME='${table.toUpperCase()}'"
    }

    @SuppressWarnings('GroovyFallthrough')
    @Override
    String getColumnDefinition(ColumnDefinition column) {
        String type = ""
        switch (column.type) {
            case boolean:
            case Boolean:
                type = "BOOLEAN"
                break
            case char:
            case Character:
                type = "CHAR"
                break
            case char[]:
                type = "CHAR(${column.length ?: 2})"
                break
            case String:
                type = column.length == UNLIMITED ? "CLOB" : "VARCHAR(${column.length ?: 255})"
                break
            case byte:
            case Byte:
                type = "TINYINT"
                break
            case short:
            case Short:
                type = "SMALLINT"
                break
            case int:
            case Integer:
            case Model:
                type = "INT"
                break
            case BigInteger:
            case long:
            case Long:
                type = "BIGINT"
                break
            case float:
            case Float:
                type = "REAL"
                break
            case double:
            case Double:
            case BigDecimal:
                type = "DOUBLE PRECISION"
                break
            case LocalDate:
                type = "DATE"
                break
            case LocalDateTime:
                type = "TIMESTAMP"
                break
            case LocalTime:
                type = "TIME"
                break
            case Inet4Address:
            case Inet6Address:
            case InetAddress:
                type = "VARCHAR(${column.length ?: 45})"
                break
            case URL:
            case URI:
                type = "VARCHAR(${column.length ?: 255})"
                break
            case Collection:
            case Map:
                type = "JSON"
                break
            case Enum:
                type = "ENUM('" + column.type.getEnumConstants().join("','") + "')"
                break
            case byte[]:
                type = "BINARY"
                break
            default:
                boolean canImport = false
                try {
                    column.type.getConstructor(String.class)
                    canImport = true
                } catch(Exception ignore) {
                    try {
                        Method method = column.type.getDeclaredMethod("fromString", String.class)
                        canImport = Modifier.isStatic(method.modifiers) && method.returnType == column.type
                    } catch(Exception ignored) {}
                }
                if(canImport) {
                    type = "VARCHAR(${column.length ?: 255})"
                } else {
                    Log.w("Unknown field type: %s", column.type.simpleName)
                }
        }
        return type
    }

    @Override
    String getIdentitySQL(String table, String columnName) {
        String cleanTable = table.replace('`', '').toUpperCase()

        return """SELECT (IDENTITY_BASE - 1) AS CURRENT_IDENTITY_VALUE FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE IS_IDENTITY = 'YES' AND TABLE_NAME = '${cleanTable}'""".stripIndent()
    }

    @Override
    String getIdentityUpdateSQL(String table, String columnName, int value) {
        return "ALTER TABLE ${table} ALTER COLUMN ${columnName ?: 'ID'} RESTART WITH ${value + 1}"
    }
}
