package com.intellisrc.db.jdbc

import com.intellisrc.core.Config
import com.intellisrc.core.Log
import com.intellisrc.core.Millis
import com.intellisrc.db.ColumnDefinition
import com.intellisrc.db.DB
import com.intellisrc.db.TableDefinition
import com.intellisrc.db.auto.AutoJDBC
import com.intellisrc.db.auto.Model
import groovy.transform.CompileStatic
import javassist.Modifier

import java.lang.reflect.Method
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime

import static com.intellisrc.db.jdbc.JDBC.BooleanHandle.*

/**
 * Oracle Database
 * @since 17/12/14.
 *
 * Additional settings:
 * db.oracle.params = [:]
 *
 * NOTE: In Oracle a user is practically the same as a schema (a collection of tables,
 * or as it is known as database in other engines). In other words, tables created
 * by that user are allocated under its tablespace. When you drop a user you can
 * also remove all tables associated with it.
 */
@CompileStatic
class Oracle extends JDBCServer implements AutoJDBC {
    String dbname = ""
    String user = "SYSTEM"
    String password = ""
    String hostname = "localhost"
    int port = 1521 // ssl port: 2484
    String driver = "oracle.jdbc.driver.OracleDriver"
    boolean supportsJSON = true
    BooleanHandle booleanHandle = BOOLEAN //Oracle 23+ supports BOOLEAN

    // Oracle specific parameters:
    // https://docs.oracle.com/cd/E13222_01/wls/docs81/jdbc_drivers/oracle.html#1066413
    // You may add more parameters as needed (values shown below are default values)
    @Override
    Map getParameters() {
        return Config.any.get("db.oracle.params", [
            BatchPerformanceWorkaround : false,
            LoginTimeout : DB.connectionTimeout * Millis.SECOND,
            ConnectionRetryCount : 3,
            ConnectionRetryDelay : 3,
            // Added:
            Boolean : true
        ] + params)
    }

    @Override
    String getConnectionString() {
        return  connectionURI ?: "oracle:thin:@//$hostname:$port/$dbname"
    }

    // QUERY BUILDING -------------------------
    // Query parameters
    boolean supportsReplace = false
    boolean convertToLowerCase = false
    boolean checkDecimals = true // Force to check
    String fieldsQuotation = '"'
    String catalogSearchName = "%"
    @Override
    String getSchemaSearchName() {
        return user.toUpperCase()
    }
    String getTableSearchName(String table) {
        return table.toUpperCase()
    }

    /**
     * FIXME: JDBC is unable to get last ID (returning some sequence string id instead, like: 'AAATPDAAHAAAALDAAB')
     *   https://community.oracle.com/tech/developers/discussion/338591/why-does-getgeneratedkeys-return-a-rowid-with-no-numeric-value
     *
     * NOTE: this method is not concurrent safe, if an insert happens between the last
     *       insert and this method, it will be incorrect (it is used as last resort)
     * @param table
     * @return
     */
    @Override
    String getLastIdQuery(String table, String pk) {
        table = table.replace(fieldsQuotation, "")
        return "SELECT ${table}_seq.currval lastId FROM dual"
    }
    /**
     * This will create a schema (user)
     * FIXME: Probably will fail due to permissions
     * @return
     */
    @Override
    String getCreateDatabaseQuery() {
        return "CREATE USER $user IDENTIFIED BY $password; GRANT ALL PRIVILEGES TO $user"
    }
    /**
     * This will remove the user with all its tables (remember that user is a schema)
     * @return
     */
    @Override
    String getDropDatabaseQuery() {
        return "DROP USER $user CASCADE"
    }

    @Override
    String getBeforeDropTableQuery(String table) {
        return "DROP SEQUENCE ${table.toLowerCase()}_seq"
    }
    /*
     * In Oracle setting the columns or table names with double quotes makes it case sensitive, but any name can be used.
     */
    @Override
    String getCreateTableSQL(String tableName, TableDefinition definitions) {
        List<String> defs = []
        List<ColumnDefinition> pks = definitions.pks
        boolean isMultiplePks = definitions.hasMultiplePk()

        // Oracle prefers uppercase identifiers for seamless data dictionary indexing
        String uTableName = tableName.toUpperCase()

        // 1. Process Columns
        definitions.each { ColumnDefinition col ->
            String uColName = col.name.toUpperCase()
            List<String> parts = ["\"${uColName}\"".toString(), getColumnDefinitionCustom(col)]

            if (!col.nullable && !col.primaryKey) {
                parts << "NOT NULL"
            }

            if (col.defaultValue) {
                // Oracle parses default values as literal configurations. Passing false is standard.
                parts << getDefaultQuery(col, false)
            }

            // Native Identity Column for modern Auto-Increment tracking
            if (col.autoIncrement) {
                parts << "GENERATED BY DEFAULT AS IDENTITY"
            }

            // Inline Primary Key for a single key table
            if (col.primaryKey && !isMultiplePks) {
                parts << "PRIMARY KEY"
            }

            // Inline Unique declarations
            if (col.unique && (col.uniqueGroup == null || col.uniqueGroup.trim().empty)) {
                parts << "UNIQUE"
            }

            defs << parts.join(' ')
        }

        // 2. Append Composite Primary Key Constraints
        if (isMultiplePks) {
            defs << "PRIMARY KEY (" + pks.collect { "\"${it.name.toUpperCase()}\"" }.join(",") + ")"
        }

        // 3. Append Composite Unique Group Constraints
        Map<String, List<String>> uniqueGroups = definitions.uniqueGroups
        if (!uniqueGroups.empty) {
            uniqueGroups.each { String groupName, List<String> columns ->
                String uGroupName = groupName.toUpperCase()
                String colsString = columns.collect { "\"${it.toUpperCase()}\"" }.join(", ")
                defs << "CONSTRAINT \"${uGroupName}\" UNIQUE (${colsString})".toString()
            }
        }

        // 4. Append Foreign Keys
        String fks = definitions.collect { getForeignKey(uTableName, it) }.findAll { it }.join(",\n")
        if (fks) {
            defs << fks
        }

        // 5. Assemble Creation Query using Oracle 23+ IF NOT EXISTS syntax
        return "CREATE TABLE IF NOT EXISTS \"${uTableName}\" (\n" + defs.join(",\n") + "\n)"
    }

    @Override
    String getCopyTableStructureSQL(String from, String to, TableDefinition columns) {
        return "CREATE TABLE \"${to.toUpperCase()}\" AS SELECT * FROM \"${from.toUpperCase()}\" WHERE 1=0"
    }

    @Override
    String getColumnDefinition(ColumnDefinition column) {
        String type = ""
        //noinspection GroovyFallthrough
        switch (column.type) {
            case boolean:
            case Boolean:
                type = switch (booleanHandle) {
                    case BOOLEAN -> "BOOLEAN"
                    case NUMBER -> "NUMBER(1,0)"
                    case CHAR -> "CHAR"
                    case ENUM -> "VARCHAR2(5) CHECK (${column.name} IN ('TRUE','FALSE'))"
                }
                break
            case char:
            case Character:
                type = "CHAR(1)"
                break
            case char[]:
                int len = column.length
                if(!len) {
                    Log.w("Column: %s is char array but has no length. Setting 2 as length.", column.name)
                    len = 2
                }
                type = "CHAR($len)"
                break
            case String:
                type = "VARCHAR2(${column.length ?: 255})"
                break
                // All numeric values share unsigned/autoincrement and primary instructions:
            case byte:
            case Byte:
                type = "NUMBER(3)"
                break
            case short:
            case Short:
                type = type ?: "NUMBER(5)"
                break
            case int:
            case Integer:
            case Model: //Another Model
                type = type ?: "NUMBER(10)"
                break
            case long:
            case Long:
                type = type ?: "NUMBER(19)"
                break
            case BigInteger:
            case BigDecimal:
                type = type ?: "NUMBER"
                break
            case float:
            case Float:
                type = "FLOAT"
                break
            case double:
            case Double:
                type = "DOUBLE PRECISION"
                break
            case LocalDate:
            case LocalDateTime:
                type = "DATE"
                break
            case LocalTime:
                type = "TIMESTAMP"
                break
            case Inet4Address:
                type = "VARCHAR2(${column.length ?: 15})"
                break
            case Inet6Address:
            case InetAddress:
                type = "VARCHAR2(${column.length ?: 45})"
                break
            case URL:
            case URI:
                boolean isUrlShort = (column.length ?: 256) <= 255
                type = (column.index || column.unique || isUrlShort) ? "VARCHAR2(${column.length ?: 255})" : "NCLOB"
                break
            case Collection:
            case Map:
                boolean isCollShort = (column.length ?: 256) <= 255
                boolean json = supportsJSON && meta && meta.hasProperty("useJson") && meta.class.getMethod("useJson").invoke(meta)
                type = (column.index || column.unique) ? "VARCHAR2(${column.length ?: 255})" : (json ? "JSON" : (isCollShort ? "VARCHAR2(${column.length ?: 255})" : "NCLOB"))
                break
            case Enum:
                List<String> constants = column.type.getEnumConstants().collect { it.toString().toUpperCase() }
                type = "VARCHAR2(${constants.max { it.length() }}) CHECK (${column.name} IN ('" + constants.join("','") + "'))"
                break
            case byte[]:
                type = "BLOB"
                break
            default:
                // Having a constructor with String or Having a static method 'fromString'
                boolean canImport = false
                try {
                    column.type.getConstructor(String.class)
                    canImport = true
                } catch(Exception ignore) {
                    try {
                        Method method = column.type.getDeclaredMethod("fromString", String.class)
                        canImport = Modifier.isStatic(method.modifiers) && method.returnType == column.type
                    } catch(Exception ignored) {}
                }
                if(canImport) {
                    int len = column.length ?: 256
                    type = len < 256 ? "VARCHAR2($len)" : "CLOB"
                } else {
                    Log.w("Unknown field type: %s", column.type.simpleName)
                    Log.v("If you want to able to use '%s' type in the database, either set `fromString` " +
                        "as static method or set a constructor which accepts `String`", column.type.simpleName)
                }
        }
        return type
    }

    @Override
    List<String> getUpdateIndicesSQL(String tableName, List<String> columns) {
        return columns.collect {
            ("CREATE INDEX IF NOT EXISTS \"${tableName}_${it}_IDX\" ON \"${tableName}\" (\"${it}\")").toString()
        }
    }

    @Override
    String getIdentitySQL(String table, String columnName) {
        return "SELECT s.last_number FROM user_sequences s JOIN user_tab_identity_cols i ON s.sequence_name = i.sequence_name WHERE i.table_name = '${table}'"
    }

    @Override
    String getIdentityUpdateSQL(String table, String columnName, int value) {
        return "ALTER TABLE ${columnName} MODIFY ${columnName} GENERATED ALWAYS AS IDENTITY (RESTART START WITH ${value + 1})"
    }

    @Override
    String getTurnFK(boolean on) {
        return """BEGIN
            FOR c IN (
                SELECT table_name, constraint_name
                FROM user_constraints
                WHERE constraint_type = 'R'
            )
            LOOP
                EXECUTE IMMEDIATE
                    'ALTER TABLE "' || c.table_name ||
                    '" ${on ? 'ENABLE' : 'DISABLE'} CONSTRAINT "' || c.constraint_name || '"';
            END LOOP;
        END;
/"""
    }

    @Override
    String getVersionRead(String table) {
        return "SELECT comments FROM user_tab_comments WHERE table_name = '${table}'"
    }

    @Override
    String getForeignKey(String tableName, ColumnDefinition column) {
        if (!column.isForeignKey) return ""
        String sql = "CONSTRAINT fk_${column.name} FOREIGN KEY (\"${column.name}\") REFERENCES `${column.referenceTable}`(`${column.referenceColumn}`) ON DELETE ${column.onDelete}"
        return sql
    }
}
