package com.intellisrc.db.jdbc

import com.intellisrc.core.Config
import com.intellisrc.core.Log
import com.intellisrc.db.ColumnDefinition
import com.intellisrc.db.DB
import com.intellisrc.db.TableDefinition
import com.intellisrc.db.auto.AutoJDBC
import com.intellisrc.db.auto.Model
import groovy.transform.CompileStatic
import javassist.Modifier

import java.lang.reflect.Method
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime

/**
 * PostgreSQL Database
 * @since 17/12/14.
 *
 * Additional settings:
 * db.postgresql.params = [:]
 *
 */
@CompileStatic
class PostgreSQL extends JDBCServer implements AutoJDBC {
    String dbname = ""
    String user = "postgres"
    String password = "password"
    String hostname = "localhost"
    int port = 5432
    String driver = "org.postgresql.Driver"
    String schemaSearchName = "public"
    // Most common:
    boolean readOnly = false
    boolean ssl = false
    boolean supportsJSON = true

    // PostgreSQL specific parameters:
    // https://jdbc.postgresql.org/documentation/head/connect.html
    // You may add more parameters as needed (values shown below are default values)
    @Override
    Map getParameters() {
        return Config.any.get("db.postgresql.params", [
            binaryTransfer      : true,
            cleanupSavepoints   : false,
            connectTimeout      : DB.connectionTimeout, //Seconds
            loginTimeout        : DB.connectionTimeout, //Seconds
            socketTimeout       : 0,    // Timeout for Queries
            readOnly            : readOnly,
            ssl                 : ssl,
            tcpKeepAlive        : false,
        ] + params)
    }
    @Override
    String getConnectionString() {
        return  connectionURI ?: "postgresql://$hostname:$port/$dbname" + (parameters.ssl ? "?ssl=true" : "")
    }

    // QUERY BUILDING -------------------------
    // Query parameters
    boolean useFetch = false
    boolean supportsReplace = false
    /**
     * Fallback for last ID
     * @param table
     * @return
     */
    @Override
    String getLastIdQuery(String table, String pk) {
        return "SELECT lastval()"
    }
    String getTruncateQuery(String table) {
        return "TRUNCATE TABLE \"$table\" CASCADE"
    }
    String getDropTableQuery(String table) {
        return "DROP TABLE \"$table\" CASCADE"
    }

    @Override
    String getCreateTableSQL(String tableName, TableDefinition definitions) {
        List<String> defs = []
        List<ColumnDefinition> pks = definitions.pks
        boolean isMultiplePks = definitions.hasMultiplePk()

        // 1. Process Columns
        definitions.each {
            ColumnDefinition col ->
                List<String> parts = ["\"${col.name}\"".toString(), getColumnDefinitionCustom(col)]

                if (col.defaultValue) {
                    // PostgreSQL evaluates defaults natively. If expressions require parenthesis,
                    // your getDefaultQuery handle should manage it. Passing false is standard for literals.
                    parts << getDefaultQuery(col, false)
                } else if (!col.nullable && !col.primaryKey) {
                    parts << "NOT NULL"
                }

                // Handle auto-increment via SQL Standard Identity columns
                if (col.autoIncrement) {
                    parts << "GENERATED BY DEFAULT AS IDENTITY"
                }

                // Inline Primary Key constraint for a single column
                if (col.primaryKey && !isMultiplePks) {
                    parts << "PRIMARY KEY"
                }

                // Inline Unique constraints
                if (col.unique && (col.uniqueGroup == null || col.uniqueGroup.trim().empty)) {
                    parts << "UNIQUE"
                }

                defs << parts.join(' ')
        }

        // 2. Append Composite Primary Key Constraints
        if (isMultiplePks) {
            defs << "PRIMARY KEY (" + pks.collect { "\"${it.name}\"" }.join(",") + ")"
        }

        // 3. Append Composite Unique Group Constraints
        Map<String, List<String>> uniqueGroups = definitions.uniqueGroups
        if (!uniqueGroups.empty) {
            uniqueGroups.each { String groupName, List<String> columns ->
                defs << "CONSTRAINT \"${groupName}\" UNIQUE (\"${columns.join('\", \"')}\")".toString()
            }
        }

        // 4. Append Foreign Keys
        String fks = definitions.collect { getForeignKey(tableName, it) }.findAll { it }.join(",\n")
        if (fks) {
            defs << fks
        }

        // 5. Assemble Main Creation Query (Supports standard IF NOT EXISTS natively)
        return "CREATE TABLE IF NOT EXISTS \"${tableName}\" (\n" + defs.join(",\n") + "\n)"
    }

    @Override
    String getColumnDefinition(ColumnDefinition column) {
        String type = ""
        boolean serial = false //column.autoIncrement
        //noinspection GroovyFallthrough
        switch (column.type) {
            case boolean:
            case Boolean:
                type = "BOOLEAN"
                break
            case char:
            case Character:
                type = "CHARACTER"
                break
            case char[]:
                int len = column.length
                if(!len) {
                    Log.w("Column: %s is char array but has no length. Setting 2 as length.", column.name)
                    len = 2
                }
                type = "CHAR($len)"
                break
            case String:
                type = "VARCHAR(${column.length ?: 255})"
                break
                // All numeric values share unsigned/autoincrement and primary instructions:
            case byte:
            case Byte:
                type = serial ? "SMALLSERIAL" : "TINYINT"
                break
            case short:
            case Short:
                type = type ?: (serial ? "SMALLSERIAL" : "SMALLINT")
                break
            case int:
            case Integer:
            case Model: //Another Model
                type = type ?: (serial ? "SERIAL" : "INTEGER")
                break
            case BigInteger:
            case long:
            case Long:
                type = type ?: (serial ? "BIGSERIAL" : "BIGINT")
                break
            case float:
            case Float:
                type = "FLOAT"
                break
            case double:
            case Double:
            case BigDecimal:
                type = "DOUBLE"
                break
            case LocalDate:
                type = "DATE"
                break
            case LocalDateTime:
                type = "DATETIME"
                break
            case LocalTime:
                type = "TIME"
                break
            case Inet4Address:
                type = "VARCHAR(${column.length ?: 15})"
                break
            case Inet6Address:
            case InetAddress:
                type = "VARCHAR(${column.length ?: 45})"
                break
            case URL:
            case URI:
                boolean isIndex = column.index || column.unique
                boolean isShort = (column.length ?: 256) <= 255
                String varChar = "VARCHAR(${column.length ?: 255})"
                type = (isIndex || isShort) ? varChar : "TEXT"
                break
            case Collection:
            case Map:
                boolean isIndex = column.index || column.unique
                boolean isShort = (column.length ?: 256) <= 255
                boolean json = supportsJSON && meta?.hasProperty("useJson") && meta?.class?.getMethod("useJson")?.invoke(meta)
                String varChar = "VARCHAR(${column.length ?: 255})"
                type = isIndex ? varChar : (json ? "JSON" : (isShort ? varChar : "TEXT"))
                break
            case Enum:
                type = "ENUM('" + column.type.getEnumConstants().join("','") + "')"
                break
            case byte[]:
                int len = column.length ?: 65535
                switch (true) {
                    case len < 256      : type = "TINYBLOB"; break
                    case len < 65536    : type = "BLOB"; break
                    case len < 16777216 : type = "MEDIUMBLOB"; break
                    default             : type = "LONGBLOB"; break
                }
                break
            default:
                // Having a constructor with String or Having a static method 'fromString'
                boolean canImport = false
                try {
                    column.type.getConstructor(String.class)
                    canImport = true
                } catch(Exception ignore) {
                    try {
                        Method method = column.type.getDeclaredMethod("fromString", String.class)
                        canImport = Modifier.isStatic(method.modifiers) && method.returnType == column.type
                    } catch(Exception ignored) {}
                }
                if(canImport) {
                    int len = column.length ?: 256
                    type = len < 256 ? "VARCHAR($len)" : "TEXT"
                } else {
                    Log.w("Unknown field type: %s", column.type.simpleName)
                    Log.v("If you want to able to use '%s' type in the database, either set `fromString` " +
                        "as static method or set a constructor which accepts `String`", column.type.simpleName)
                }
        }
        return type
    }

    @Override
    List<String> getUpdateIndicesSQL(String tableName, List<String> columns) {
        return columns.collect {
            ("CREATE INDEX IF NOT EXISTS \"${tableName}_${it}_idx\" ON \"${tableName}\" (\"${it}\")").toString()
        }
    }

    @Override
    String getTurnFK(boolean on) {
        return String.format("SET session_replication_role = '%s'", on ? "origin" : "replica")
    }

    @Override
    String getCopyTableStructureSQL(String from, String to, TableDefinition columns) {
        return "CREATE TABLE \"$to\" (LIKE \"$from\" INCLUDING ALL)"
    }

    @Override
    String getVersionRead(String table) {
        return "SELECT obj_description(to_regclass('public.${table}'))"
    }

    @Override
    String getIdentitySQL(String table, String columnName) {
        String cleanTable = table.replace('"', '').toLowerCase()
        String cleanCol = columnName.replace('"', '').toLowerCase()

        // We extract the sequence name using pg_get_serial_sequence,
        // then look it up in pg_sequences to get the true last_value or start_value
       /* return """SELECT COALESCE(s.last_value) FROM pg_sequences s
        WHERE s.sequencename = substring(pg_get_serial_sequence('"${cleanTable}"', '${cleanCol}') from '[^.]+\$')""".stripIndent()*/
        return """SELECT CASE WHEN is_called THEN last_value ELSE last_value - 1 END FROM ${cleanTable}_${cleanCol}_seq"""
    }

    @Override
    String getIdentityUpdateSQL(String table, String columnName, int value) {
        return "ALTER TABLE \"${table}\" ALTER COLUMN \"${columnName}\" RESTART WITH ${value + 1}"
    }
}
