package com.intellisrc.db.jdbc

import com.intellisrc.core.Config
import com.intellisrc.core.Log
import com.intellisrc.db.DB
import com.intellisrc.db.Query
import com.intellisrc.db.ColumnDefinition
import com.intellisrc.db.TableDefinition
import com.intellisrc.db.auto.AutoJDBC
import com.intellisrc.db.auto.Model
import groovy.transform.CompileStatic
import javassist.Modifier

import java.lang.reflect.Constructor
import java.lang.reflect.Method
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.util.regex.Matcher

import static com.intellisrc.db.auto.Relational.getColumnName

/**
 * PostgreSQL Database
 * @since 17/12/14.
 *
 * Additional settings:
 * db.postgresql.params = [:]
 *
 */
@CompileStatic
class PostgreSQL extends JDBCServer implements AutoJDBC {
    String dbname = ""
    String user = "postgres"
    String password = "password"
    String hostname = "localhost"
    int port = 5432
    String driver = "org.postgresql.Driver"
    String schemaSearchName = "public"
    // Most common:
    boolean readOnly = false
    boolean ssl = false
    boolean supportsJSON = true
    // PostgreSQL specific parameters:
    // https://jdbc.postgresql.org/documentation/head/connect.html
    // You may add more parameters as needed (values shown below are default values)
    @Override
    Map getParameters() {
        return Config.any.get("db.postgresql.params", [
            binaryTransfer      : true,
            cleanupSavepoints   : false,
            connectTimeout      : DB.connectionTimeout, //Seconds
            loginTimeout        : DB.connectionTimeout, //Seconds
            socketTimeout       : 0,    // Timeout for Queries
            readOnly            : readOnly,
            ssl                 : ssl,
            tcpKeepAlive        : false,
        ] + params)
    }
    @Override
    String getConnectionString() {
        return  connectionURI ?: "postgresql://$hostname:$port/$dbname" + (parameters.ssl ? "?ssl=true" : "")
    }

    // QUERY BUILDING -------------------------
    // Query parameters
    boolean useFetch = false
    boolean supportsReplace = false
    /**
     * Fallback for last ID
     * @param table
     * @return
     */
    @Override
    String getLastIdQuery(String table, String pk) {
        return "SELECT lastval()"
    }
    String getTruncateQuery(String table) {
        return "TRUNCATE TABLE \"$table\" CASCADE"
    }
    String getDropTableQuery(String table) {
        return "DROP TABLE \"$table\" CASCADE"
    }

    @Override
    boolean createTable(String tableName, TableDefinition definitions = [] as TableDefinition, String charset = "", String engine = "", int version = 1) {
        List<String> defs = []
        List<String> keys = [] // Holds independent index queries
        List<ColumnDefinition> pks = definitions.pks
        boolean isMultiplePks = definitions.hasMultiplePk()

        // 1. Process Columns
        definitions.each {
            ColumnDefinition col ->
                List<String> parts = ["\"${col.name}\"".toString(), getColumnDefinitionCustom(col)]

                if (!col.nullable && !col.primaryKey) {
                    parts << "NOT NULL"
                }

                if (col.defaultValue) {
                    // PostgreSQL evaluates defaults natively. If expressions require parenthesis,
                    // your getDefaultQuery handle should manage it. Passing false is standard for literals.
                    parts << getDefaultQuery(col, false)
                }

                // Handle auto-increment via SQL Standard Identity columns
                if (col.autoIncrement) {
                    parts << "GENERATED BY DEFAULT AS IDENTITY"
                }

                // Inline Primary Key constraint for a single column
                if (col.primaryKey && !isMultiplePks) {
                    parts << "PRIMARY KEY"
                }

                // Inline Unique constraints
                if (col.unique && (col.uniqueGroup == null || col.uniqueGroup.trim().empty)) {
                    parts << "UNIQUE"
                }

                defs << parts.join(' ')

                // Collect index definitions to run as separate queries later
                if (col.index) {
                    keys << ("CREATE INDEX IF NOT EXISTS \"${tableName}_${col.name}_idx\" ON \"${tableName}\" (\"${col.name}\")").toString()
                }
        }

        // 2. Append Composite Primary Key Constraints
        if (isMultiplePks) {
            defs << "PRIMARY KEY (" + pks.collect { "\"${it.name}\"" }.join(",") + ")"
        }

        // 3. Append Composite Unique Group Constraints
        Map<String, List<String>> uniqueGroups = definitions.uniqueGroups
        if (!uniqueGroups.empty) {
            uniqueGroups.each { String groupName, List<String> columns ->
                defs << "CONSTRAINT \"${groupName}\" UNIQUE (\"${columns.join('\", \"')}\")".toString()
            }
        }

        // 4. Append Foreign Keys
        String fks = definitions.collect { getForeignKey(tableName, it) }.findAll { it }.join(",\n")
        if (fks) {
            defs << fks
        }

        // 5. Assemble Main Creation Query (Supports standard IF NOT EXISTS natively)
        String createSQL = "CREATE TABLE IF NOT EXISTS \"${tableName}\" (\n" + defs.join(",\n") + "\n)"

        DB db = connect()
        boolean ok = db.set(new Query(createSQL))

        if (ok) {
            // Execute table indices sequentially upon successful table validation
            keys.each {
                String indexSql ->
                    if (!db.set(new Query(indexSql))) {
                        Log.w("Failed to create PostgreSQL index: %s", indexSql)
                    }
            }

            // Optional: Apply schema version tracking as a standard table COMMENT
            if (version > 0) {
                String commentSql = "COMMENT ON TABLE \"${tableName}\" IS 'v.${version}'"
                db.set(new Query(commentSql))
            }
        } else {
            Log.v(createSQL)
            Log.e("Unable to create PostgreSQL table.")
        }
        db.close()
        return ok
    }

    @Override
    String getColumnDefinition(ColumnDefinition column) {
        String type = ""
        boolean serial = false //column.autoIncrement
        //noinspection GroovyFallthrough
        switch (column.type) {
            case boolean:
            case Boolean:
                type = "BOOLEAN"
                break
            case char:
            case Character:
                type = "CHARACTER"
                break
            case char[]:
                int len = column.length
                if(!len) {
                    Log.w("Column: %s is char array but has no length. Setting 2 as length.", column.name)
                    len = 2
                }
                type = "CHAR($len)"
                break
            case String:
                type = "VARCHAR(${column.length ?: 255})"
                break
                // All numeric values share unsigned/autoincrement and primary instructions:
            case byte:
            case Byte:
                type = serial ? "SMALLSERIAL" : "TINYINT"
                break
            case short:
            case Short:
                type = type ?: (serial ? "SMALLSERIAL" : "SMALLINT")
                break
            case int:
            case Integer:
            case Model: //Another Model
                type = type ?: (serial ? "SERIAL" : "INTEGER")
                break
            case BigInteger:
            case long:
            case Long:
                type = type ?: (serial ? "BIGSERIAL" : "BIGINT")
                break
            case float:
            case Float:
                type = "FLOAT"
                break
            case double:
            case Double:
            case BigDecimal:
                type = "DOUBLE"
                break
            case LocalDate:
                type = "DATE"
                break
            case LocalDateTime:
                type = "DATETIME"
                break
            case LocalTime:
                type = "TIME"
                break
            case Inet4Address:
                type = "VARCHAR(${column.length ?: 15})"
                break
            case Inet6Address:
            case InetAddress:
                type = "VARCHAR(${column.length ?: 45})"
                break
            case URL:
            case URI:
                boolean isIndex = column.index || column.unique
                boolean isShort = (column.length ?: 256) <= 255
                String varChar = "VARCHAR(${column.length ?: 255})"
                type = (isIndex || isShort) ? varChar : "TEXT"
                break
            case Collection:
            case Map:
                boolean isIndex = column.index || column.unique
                boolean isShort = (column.length ?: 256) <= 255
                boolean json = supportsJSON && meta?.hasProperty("useJson") && meta?.class?.getMethod("useJson")?.invoke(meta)
                String varChar = "VARCHAR(${column.length ?: 255})"
                type = isIndex ? varChar : (json ? "JSON" : (isShort ? varChar : "TEXT"))
                break
            case Enum:
                type = "ENUM('" + column.type.getEnumConstants().join("','") + "')"
                break
            case byte[]:
                int len = column.length ?: 65535
                switch (true) {
                    case len < 256      : type = "TINYBLOB"; break
                    case len < 65536    : type = "BLOB"; break
                    case len < 16777216 : type = "MEDIUMBLOB"; break
                    default             : type = "LONGBLOB"; break
                }
                break
            default:
                // Having a constructor with String or Having a static method 'fromString'
                boolean canImport = false
                try {
                    column.type.getConstructor(String.class)
                    canImport = true
                } catch(Exception ignore) {
                    try {
                        Method method = column.type.getDeclaredMethod("fromString", String.class)
                        canImport = Modifier.isStatic(method.modifiers) && method.returnType == column.type
                    } catch(Exception ignored) {}
                }
                if(canImport) {
                    int len = column.length ?: 256
                    type = len < 256 ? "VARCHAR($len)" : "TEXT"
                } else {
                    Log.w("Unknown field type: %s", column.type.simpleName)
                    Log.v("If you want to able to use '%s' type in the database, either set `fromString` " +
                        "as static method or set a constructor which accepts `String`", column.type.simpleName)
                }
        }
        return type
    }

    @Override
    String getForeignKey(String tableName, ColumnDefinition column) {
        String indices = ""
        switch (column.type) {
            case Model:
                Constructor<?> ctor = column.type.getConstructor()
                Model refType = (ctor.newInstance() as Model)
                String joinTable = refType.tableName
                String action = column.onDelete.toString()
                indices = "FOREIGN KEY (\"${column.name}\") " +
                    "REFERENCES \"${joinTable}\"(\"${getColumnName(refType.primaryKey)}\") ON DELETE ${action}"
                break
        }
        return indices
    }

    @Override
    boolean turnFK(boolean on) {
        return set(String.format("SET session_replication_role = '%s'", on ? "origin" : "replica"))
    }
    @Override
    boolean copyTableStructure(String from, String to) {
        return false //set(db, "CREATE TABLE \"$to\" (LIKE \"$from\" INCLUDING ALL)")
    }
    @Override
    boolean copyTableData(String from, String to, TableDefinition columns) {
        return set("INSERT INTO \"${to}\" (SELECT * FROM ${from})")
    }
    @Override
    boolean resetAutoIncrement(String field) {
        // 1. Identify the current maximum ID inside the newly populated table
        int maxId = get("SELECT COALESCE(MAX(\"${field}\"), 0) FROM \"${name}\"").toInt()
        // 2. The next auto-increment value should pick up exactly at max + 1
        int nextValue = maxId + 1
        // 3. Reset the standard identity tracker directly using a simple DDL alteration
        return set("ALTER TABLE \"${name}\" ALTER COLUMN \"${field}\" RESTART WITH ${nextValue}")
    }

    @Override
    boolean copyAutoIncrement(String tableFrom, String tableTo, String columnName) {
        DB db = connect()
        boolean ok = false
        // 1. Resolve the sequence name tracking the source table
        String seqFromQry = "SELECT pg_get_serial_sequence('\"${tableFrom}\"', '${columnName}')"
        String seqFrom = db.get(new Query(seqFromQry)).toString()

        if (seqFrom && seqFrom != "null") {
            // 2. Fetch the last value that the sequence generated
            long currentVal = db.get(new Query("SELECT last_value FROM ${seqFrom}")).toLong()
            boolean isCalled = db.get(new Query("SELECT is_called FROM ${seqFrom}")).toBool()

            // 3. Resolve the target sequence and sync the value state perfectly
            String seqToQry = "SELECT pg_get_serial_sequence('\"${tableTo}\"', '${columnName}')"
            String seqTo = db.get(new Query(seqToQry)).toString()
            ok = db.set(new Query("SELECT setval('${seqTo}', ${currentVal}, ${isCalled})"))
        }
        db.close()
        return ok
    }
    @Override
    boolean setVersion(String dbname, String table, int version) {
        return set("COMMENT ON TABLE \"${table}\" IS 'v.${version}'")
    }
    @Override
    int getVersion(String dbname, String table) {
        String verStr = get("SELECT obj_description(to_regclass('public.${table}'))").toString()
        int version = 1
        if(verStr && verStr != "null") {
            Matcher matcher = (verStr =~ /(\d+)/)
            if(matcher.find()) {
                version = matcher.group(1) as int
            }
        }
        return version
    }
}
