dependencies {
    api project(':etc')

    def reflections= "0.10.2"

    def derby       = '10.17.1.0'       // After 10.16.1.1 it is compiled with Java 17
    def firebird    = '6.0.4'           // firebird 6.0+ requires Java 17
    def h2          = '2.4.240'
    def hypersql    = '2.7.4'
    def mariadb     = '3.5.7'
    def mysql       = '9.5.0'
    def oracle      = '23.26.0.0.0' //'21.9.0.0'        // test container is 21
    //def oracle      = '23.3.0.23.09' <-- not ready (failing tests). May need code changes
    def postgresql  = '42.7.9'
    def sqlite      = '3.51.1.0'
    def sqlserver   = '13.2.1.jre11'

    api "org.reflections:reflections:${reflections}"
    // We set connectors as optional because most likely only one will be used and
    // depending on which server its being used, another version may be required.

    //compileOnly "org.apache.derby:derbyclient:${derby}" // This one includes only the JDBC client driver
    compileOnly "org.apache.derby:derby:${derby}" // This one includes also the database engine
    compileOnly "org.firebirdsql.jdbc:jaybird:${firebird}"
    compileOnly "com.h2database:h2:${h2}"
    compileOnly "org.hsqldb:hsqldb:${hypersql}"
    compileOnly "org.mariadb.jdbc:mariadb-java-client:${mariadb}"
    compileOnly "com.mysql:mysql-connector-j:${mysql}"
    compileOnly "com.oracle.database.jdbc:ojdbc11:${oracle}"
    compileOnly "org.postgresql:postgresql:${postgresql}"
    compileOnly "org.xerial:sqlite-jdbc:${sqlite}"
    compileOnly "com.microsoft.sqlserver:mssql-jdbc:${sqlserver}"

    // NOTE: it seems repetitive, but it was done like that, so IntelliJ can identify dependencies versions.
    testImplementation project(':net')
    testImplementation project(':term')
    testImplementation project(':log')
    testImplementation "org.apache.derby:derby:${derby}" // This one includes also the database engine
    testImplementation "org.firebirdsql.jdbc:jaybird:${firebird}"
    testImplementation "com.h2database:h2:${h2}"
    testImplementation "org.hsqldb:hsqldb:${hypersql}"
    testImplementation "org.mariadb.jdbc:mariadb-java-client:${mariadb}"
    testImplementation "com.mysql:mysql-connector-j:${mysql}"
    testImplementation "com.oracle.database.jdbc:ojdbc11:${oracle}"
    testImplementation "org.postgresql:postgresql:${postgresql}"
    testImplementation "org.xerial:sqlite-jdbc:${sqlite}"
    testImplementation "com.microsoft.sqlserver:mssql-jdbc:${sqlserver}"
}

repositories {
    mavenCentral()
}