dependencies {
    api project(':etc')

    def reflections= "0.10.2"

    def h2          = '2.4.240'
    def mariadb     = '3.5.10'
    def mysql       = '26.7.0'
    def oracle      = '23.26.3.0.0' //'21.9.0.0'        // test container is 21
    //def oracle      = '23.3.0.23.09' <-- not ready (failing tests). May need code changes
    def postgresql  = '42.7.13'
    def sqlite      = '3.53.2.1'
    def sqlserver   = '13.4.0.jre11'

    api "org.reflections:reflections:${reflections}"
    // We set connectors as optional because most likely only one will be used and
    // depending on which server its being used, another version may be required.

    compileOnly "com.h2database:h2:${h2}"
    compileOnly "org.mariadb.jdbc:mariadb-java-client:${mariadb}"
    compileOnly "com.mysql:mysql-connector-j:${mysql}"
    compileOnly "com.oracle.database.jdbc:ojdbc11:${oracle}"
    compileOnly "org.postgresql:postgresql:${postgresql}"
    compileOnly "org.xerial:sqlite-jdbc:${sqlite}"
    compileOnly "com.microsoft.sqlserver:mssql-jdbc:${sqlserver}"

    // NOTE: it seems repetitive, but it was done like that, so IntelliJ can identify dependencies versions.
    testImplementation project(':net')
    testImplementation project(':term')
    testImplementation project(':log')
    testImplementation "com.h2database:h2:${h2}"
    testImplementation "org.mariadb.jdbc:mariadb-java-client:${mariadb}"
    testImplementation "com.mysql:mysql-connector-j:${mysql}"
    testImplementation "com.oracle.database.jdbc:ojdbc11:${oracle}"
    testImplementation "org.postgresql:postgresql:${postgresql}"
    testImplementation "org.xerial:sqlite-jdbc:${sqlite}"
    testImplementation "com.microsoft.sqlserver:mssql-jdbc:${sqlserver}"
}

repositories {
    mavenCentral()
}